# .github/workflows/deploy.yml
name: SWEtim Build and Deploy

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker Buildx 설정 (캐시 사용)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 캐시와 함께 빌드 및 푸시
      - name: Build and push with Cache
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/swetim:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 5. 홈서버 배포
      - name: Deploy to Home Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # /tmp/swe-deploy.lock 파일을 기준으로 잠금을 시도
            # -w 120 : 최대 120초(2분) 동안 잠금
            # -c "..." : 잠금에 성공하면 "..." 안의 명령어를 실행
            flock -w 120 /tmp/swe-deploy.lock -c " \
              echo 'Deploy Lock Acquired by ${{ github.workflow }}, starting deploy...'; \
              cd ~/project/swe; \
              docker pull ${{ secrets.DOCKER_USERNAME }}/swetim:latest; \
              docker compose up -d --force-recreate; \
              docker image prune -f; \
              echo 'Deploy ${{ github.workflow }} Finished, Releasing Lock.'; \
            "
